-- BoxOps - remove duplicate FK helper index.
--
-- `coach_profiles_org_user_idx` already covers `(organization_id, user_id)`.
-- Keep the older named index and remove the duplicate generated by the
-- catalog-driven FK index migration.

DROP INDEX IF EXISTS public.coach_profiles_organization_id_user_id_fk_idx_f602512e;
